/usr/lib/*/qt5/plugins/kcms/kcm_mobile_hotspot.so
/usr/lib/*/qt5/plugins/kcms/kcm_wifi.so
/usr/share/kpackage/kcms/kcm_mobile_hotspot/
/usr/share/kpackage/kcms/kcm_wifi
/usr/share/kservices5/hotspotsettings.desktop
/usr/share/kservices5/wifisettings.desktop

/usr/share/locale/*/LC_MESSAGES/kcm_wifi.mo

/usr/share/kpackage/kcms/kcm_wifi/contents/ui/ConnectedItem.qml
/usr/share/kpackage/kcms/kcm_wifi/contents/ui/DNS.qml
/usr/share/kpackage/kcms/kcm_wifi/contents/ui/Home.qml
/usr/share/kpackage/kcms/kcm_wifi/contents/ui/InputItem.qml
/usr/share/kpackage/kcms/kcm_wifi/contents/ui/IPV4.qml
/usr/share/kpackage/kcms/kcm_wifi/contents/ui/main.qml
/usr/share/kpackage/kcms/kcm_wifi/contents/ui/NormalInputItem.qml
/usr/share/kpackage/kcms/kcm_wifi/contents/ui/Password.qml
/usr/share/kpackage/kcms/kcm_wifi/contents/ui/SelectItem.qml
/usr/share/kpackage/kcms/kcm_wifi/contents/ui/SwitchItem.qml
/usr/share/kpackage/kcms/kcm_wifi/contents/ui/WifiItem.qml

